#!/usr/bin/env python3
"""
TTH Books Configuration
=======================

Configuration data for all supported TTH books.
"""

from pathlib import Path
from typing import Dict, Any

# Base paths
DATA_PATH = Path.home() / 'davar' / 'data' / 'tth'
RAW_PATH = DATA_PATH / 'raw'
DRAFT_PATH = DATA_PATH / 'draft'
TEMP_PATH = DATA_PATH / 'temp'

# Source documents
TANAJ_MD = RAW_PATH / 'tanaj.md'
BESORAH_MD = RAW_PATH / 'besorah.md'

# Book information database
BOOKS_INFO: Dict[str, Dict[str, Any]] = {
    # Torah (Pentateuco)
    'bereshit': {
        'tth_name': 'Bereshit',
        'hebrew_name': 'בראשית',
        'english_name': 'Genesis',
        'spanish_name': 'Génesis',
        'book_code': 'genesis',
        'expected_chapters': 50,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'source': 'tanaj',
        'start_pattern': r'^__.*BERESHIT.*בראשית',
        'end_patterns': ['__SHEMOT', 'שמות'],
    },
    'shemot': {
        'tth_name': 'Shemot',
        'hebrew_name': 'שמות',
        'english_name': 'Exodus',
        'spanish_name': 'Éxodo',
        'book_code': 'exodus',
        'expected_chapters': 40,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'source': 'tanaj',
        'start_pattern': r'SHEMOT.*שמות',
        'end_patterns': ['VAIKRÁ', 'ויקרא'],
    },
    'vaikra': {
        'tth_name': 'Vaikra',
        'hebrew_name': 'ויקרא',
        'english_name': 'Leviticus',
        'spanish_name': 'Levítico',
        'book_code': 'leviticus',
        'expected_chapters': 27,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'source': 'tanaj',
        'start_pattern': r'VAIKRÁ.*ויקרא',
        'end_patterns': ['BAMIDBAR', 'במדבר'],
    },
    'bamidbar': {
        'tth_name': 'Bamidbar',
        'hebrew_name': 'במדבר',
        'english_name': 'Numbers',
        'spanish_name': 'Números',
        'book_code': 'numbers',
        'expected_chapters': 36,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'source': 'tanaj',
        'start_pattern': r'BAMIDBAR.*במדבר',
        'end_patterns': ['DEVARIM', 'דברים'],
    },
    'devarim': {
        'tth_name': 'Devarim',
        'hebrew_name': 'דברים',
        'english_name': 'Deuteronomy',
        'spanish_name': 'Deuteronomio',
        'book_code': 'deuteronomy',
        'expected_chapters': 34,
        'section': 'torah',
        'section_hebrew': 'תורה',
        'section_english': 'Torah',
        'section_spanish': 'Torá',
        'source': 'tanaj',
        'start_pattern': r'DEVARIM.*דברים',
        'end_patterns': ['NEVIÍM', 'IEHOSHÚA', 'יהושע'],
    },

    # Neviim (Profetas)
    'iehoshua': {
        'tth_name': 'Iehoshúa',
        'hebrew_name': 'יהושע',
        'english_name': 'Joshua',
        'spanish_name': 'Josué',
        'book_code': 'joshua',
        'expected_chapters': 24,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IEHOSHÚA.*יהושע|NEVIÍM.*IEHOSHÚA',
        'end_patterns': ['SHOFTÍM', 'שפטים'],
    },
    'shoftim': {
        'tth_name': 'Shoftim',
        'hebrew_name': 'שפטים',
        'english_name': 'Judges',
        'spanish_name': 'Jueces',
        'book_code': 'judges',
        'expected_chapters': 21,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'SHOFTÍM.*שפטים',
        'end_patterns': ['SHEMUEL', 'שמואל'],
    },
    'shemuel_alef': {
        'tth_name': 'Shemuel Alef',
        'hebrew_name': 'א שמואל',
        'english_name': '1 Samuel',
        'spanish_name': '1 Samuel',
        'book_code': '1_samuel',
        'expected_chapters': 31,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'SHEMUEL\s*ALEF|SHEMUEL\s*Á?LEF.*א\s*שמואל',
        'end_patterns': ['SHEMUEL BET', 'ב שמואל'],
    },
    'shemuel_bet': {
        'tth_name': 'Shemuel Bet',
        'hebrew_name': 'ב שמואל',
        'english_name': '2 Samuel',
        'spanish_name': '2 Samuel',
        'book_code': '2_samuel',
        'expected_chapters': 24,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'SHEMUEL\s*BET.*ב\s*שמואל',
        'end_patterns': ['MELAJIM', 'מלכים'],
    },
    'melajim_alef': {
        'tth_name': 'Melajim Alef',
        'hebrew_name': 'א מלכים',
        'english_name': '1 Kings',
        'spanish_name': '1 Reyes',
        'book_code': '1_kings',
        'expected_chapters': 22,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'MELAJIM\s*ALEF|MELAJIM\s*Á?LEF.*א\s*מלכים',
        'end_patterns': ['MELAJIM BET', 'ב מלכים'],
    },
    'melajim_bet': {
        'tth_name': 'Melajim Bet',
        'hebrew_name': 'ב מלכים',
        'english_name': '2 Kings',
        'spanish_name': '2 Reyes',
        'book_code': '2_kings',
        'expected_chapters': 25,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'MELAJIM\s*BET.*ב\s*מלכים',
        'end_patterns': ['IESHAIÁHU', 'ישעיהו'],
    },
    'ieshaiahu': {
        'tth_name': 'Ieshaiáhu',
        'hebrew_name': 'ישעיהו',
        'english_name': 'Isaiah',
        'spanish_name': 'Isaías',
        'book_code': 'isaiah',
        'expected_chapters': 66,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IESHAIÁHU.*ישעיהו',
        'end_patterns': ['IRMEIÁHU', 'ירמיהו'],
    },
    'irmeiahu': {
        'tth_name': 'Irmeiáhu',
        'hebrew_name': 'ירמיהו',
        'english_name': 'Jeremiah',
        'spanish_name': 'Jeremías',
        'book_code': 'jeremiah',
        'expected_chapters': 52,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IRMEIÁHU.*ירמיהו',
        'end_patterns': ['IEJEZKEL', 'יחזקאל'],
    },
    'iejezkel': {
        'tth_name': 'Iejezkel',
        'hebrew_name': 'יחזקאל',
        'english_name': 'Ezekiel',
        'spanish_name': 'Ezequiel',
        'book_code': 'ezekiel',
        'expected_chapters': 48,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IEJEZKEL.*יחזקאל',
        'end_patterns': ['HOSHEA', 'הושע'],
    },
    'hoshea': {
        'tth_name': 'Hoshea',
        'hebrew_name': 'הושע',
        'english_name': 'Hosea',
        'spanish_name': 'Oseas',
        'book_code': 'hosea',
        'expected_chapters': 14,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'HOSHEA.*הושע',
        'end_patterns': ['IOEL', 'יואל'],
    },
    'ioel': {
        'tth_name': 'Ioel',
        'hebrew_name': 'יואל',
        'english_name': 'Joel',
        'spanish_name': 'Joel',
        'book_code': 'joel',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IOEL.*יואל',
        'end_patterns': ['AMÓS', 'עמוס'],
    },
    'amos': {
        'tth_name': 'Amós',
        'hebrew_name': 'עמוס',
        'english_name': 'Amos',
        'spanish_name': 'Amós',
        'book_code': 'amos',
        'expected_chapters': 9,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'__AMÓS__\s*עמוס',
        'end_patterns': ['OBADIAH', 'OVADIAH', 'OBADIÁH', 'עבדיה'],
    },
    'obadiah': {
        'tth_name': 'Obadiáh',
        'hebrew_name': 'עבדיה',
        'english_name': 'Obadiah',
        'spanish_name': 'Abdías',
        'book_code': 'obadiah',
        'expected_chapters': 1,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'OBADIÁH.*עבדיה|OBADIAH.*עבדיה',
        'end_patterns': ['IONAH', 'IONÁH', 'יונה'],
    },
    'ionah': {
        'tth_name': 'Ionah',
        'hebrew_name': 'יונה',
        'english_name': 'Jonah',
        'spanish_name': 'Jonás',
        'book_code': 'jonah',
        'expected_chapters': 4,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'IONÁH.*יונה|IONAH.*יונה',
        'end_patterns': ['MICÁH', 'MICAH', 'מיכה'],
    },
    'micah': {
        'tth_name': 'Micah',
        'hebrew_name': 'מיכה',
        'english_name': 'Micah',
        'spanish_name': 'Miqueas',
        'book_code': 'micah',
        'expected_chapters': 7,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'MICÁH.*מיכה|MICAH.*מיכה',
        'end_patterns': ['NAJUM', 'נחום'],
    },
    'najum': {
        'tth_name': 'Najum',
        'hebrew_name': 'נחום',
        'english_name': 'Nahum',
        'spanish_name': 'Nahúm',
        'book_code': 'nahum',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'NAJUM.*נחום',
        'end_patterns': ['JABAKUK', 'חבקוק'],
    },
    'jabakuk': {
        'tth_name': 'Jabakuk',
        'hebrew_name': 'חבקוק',
        'english_name': 'Habakkuk',
        'spanish_name': 'Habacuc',
        'book_code': 'habakkuk',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'JABAKUK.*חבקוק',
        'end_patterns': ['TZEFANIAH', 'TZEFANIÁH', 'צפניה'],
    },
    'tzefaniah': {
        'tth_name': 'Tzefaniah',
        'hebrew_name': 'צפניה',
        'english_name': 'Zephaniah',
        'spanish_name': 'Sofonías',
        'book_code': 'zephaniah',
        'expected_chapters': 3,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'TZEFANIÁH.*צפניה|TZEFANIAH.*צפניה',
        'end_patterns': ['JAGAI', 'חגי'],
    },
    'jagai': {
        'tth_name': 'Jagai',
        'hebrew_name': 'חגי',
        'english_name': 'Haggai',
        'spanish_name': 'Hageo',
        'book_code': 'haggai',
        'expected_chapters': 2,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'JAGAI.*חגי',
        'end_patterns': ['ZEJARIAH', 'ZEJARIÁH', 'זכריה'],
    },
    'zejariah': {
        'tth_name': 'Zejariah',
        'hebrew_name': 'זכריה',
        'english_name': 'Zechariah',
        'spanish_name': 'Zacarías',
        'book_code': 'zechariah',
        'expected_chapters': 14,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'ZEJARIÁH.*זכריה|ZEJARIAH.*זכריה',
        'end_patterns': ['MALAJÍ', 'MALAJI', 'מלאכי'],
    },
    'malaji': {
        'tth_name': 'Malaji',
        'hebrew_name': 'מלאכי',
        'english_name': 'Malachi',
        'spanish_name': 'Malaquías',
        'book_code': 'malachi',
        'expected_chapters': 4,
        'section': 'neviim',
        'section_hebrew': 'נביאים',
        'section_english': 'Prophets',
        'section_spanish': 'Profetas',
        'source': 'tanaj',
        'start_pattern': r'MALAJÍ.*מלאכי|MALAJI.*מלאכי',
        'end_patterns': ['KETUVIM', 'TEHILIM', 'תהלים'],
    },

    # Ketuvim (Escritos)
    'tehilim': {
        'tth_name': 'Tehilim',
        'hebrew_name': 'תהלים',
        'english_name': 'Psalms',
        'spanish_name': 'Salmos',
        'book_code': 'psalms',
        'expected_chapters': 150,
        'section': 'ketuvim',
        'section_hebrew': 'כתובים',
        'section_english': 'Writings',
        'section_spanish': 'Escritos',
        'source': 'tanaj',
        'start_pattern': r'KETUVIM.*TEHILIM|TEHILIM.*תהלים',
        'end_patterns': ['MISHLEI', 'משלי'],
    },
    'mishlei': {
        'tth_name': 'Mishlei',
        'hebrew_name': 'משלי',
        'english_name': 'Proverbs',
        'spanish_name': 'Proverbios',
        'book_code': 'proverbs',
        'expected_chapters': 31,
        'section': 'ketuvim',
        'section_hebrew': 'כתובים',
        'section_english': 'Writings',
        'section_spanish': 'Escritos',
        'source': 'tanaj',
        'start_pattern': r'MISHLEI.*משלי',
        'end_patterns': ['IOB', 'איוב', r'\[\^\d+\]:'],  # End at footnotes or next book
    },
}

# Hebrew terms dictionary
HEBREW_TERMS = {
    'YEHOVAH': 'Tetragrámaton - Nombre de Elohim',
    'Yehovah': 'Tetragrámaton - Nombre de Elohim',
    'יהוה': 'Tetragrámaton - Nombre de Elohim',
    'Yeshúa': 'Jesús en hebreo',
    'Mesías': 'El Ungido, Cristo',
    'Elohim': 'Dios, Poderoso',
    'Eloah': 'Singular de Elohim',
    'Elohah': 'Singular de Elohim',
    'EL': 'Versión corta de Elohim',
    'Adón': 'Señor, Amo',
    'Adonai': 'Señor, Amo',
    'Rúaj': 'Espíritu, viento, aliento',
    "Ha'Kódesh": 'Santo',
    "Rúaj Ha'Kódesh": 'Espíritu de Santidad',
    'emunah': 'fe, fidelidad, constancia',
    'shalom': 'paz, bienestar completo',
    "Ha'Satán": 'El adversario',
    "Ha'satán": 'El adversario',
    'Kadosh': 'Apartado, Santo',
    'Teshuváh': 'Retorno, arrepentimiento',
    'Malajim': 'Mensajeros, ángeles',
    'malaj': 'mensajero, ángel',
    'Tzebaot': 'Ejércitos',
    'Hejal': 'Santuario, Templo',
    'Ierushaláim': 'Jerusalén',
    'Ierushalem': 'Jerusalén',
    'Iehudáh': 'Judá',
    'Iehudí': 'Judío',
    'Iehudim': 'Judíos',
    'iehudim': 'Judíos',
    'Mitzráim': 'Egipto',
    'mitzrim': 'Egipcios',
    'mitzrit': 'Egipcia',
    'Shofar': 'Cuerno de carnero',
    'shofarot': 'Cuernos de carnero (plural)',
    'Gei Hinom': 'Valle de Hinom, Gehena',
    'Guei Hinom': 'Valle de Hinom, Gehena',
    'Iojanán': 'Juan',
    'Iaacob': 'Santiago, Jacobo',
    'Moshéh': 'Moisés',
    'Rajab': 'Rahab',
    'Rujot': 'Espíritus, Vientos (plural)',
    'Galil': 'Galilea',
    'Iardén': 'Jordán',
    'Bet Léjem': 'Belén',
    'Natzrat': 'Nazaret',
    'Notzrí': 'Nazareno',
    'Pésaj': 'Pascua',
    'tefilah': 'oración',
    "Ben Ha'Adam": 'Hijo del Hombre',
    'av': 'Padre',
    'olam': 'mundo, era, tiempo',
    'man': 'Maná',
    'Rabí': 'Rabino, Maestro',
    'perushim': 'Fariseos',
    'tzadikim': 'Saduceos',
    'shomroní': 'Samaritano',
    'guelilí': 'Galileo',
    'Ieshaiáhu': 'Isaías',
    'Irmiáh': 'Jeremías',
    'Ionah': 'Jonás',
    'Eliyáhu': 'Elías',
    'Shelomóh': 'Salomón',
    'Migdalit': 'Magdalena',
    'kirení': 'Cireneo',
    'Gólgota': 'Gólgota',
    'Gulgolet': 'Calavera',
    'goral': 'suerte, suertes',
    'Matzot': 'Pan sin levadura',
    'Ish-Kariot': 'Iscariote',
    'Bet Aniah': 'Betania',
    'Eleazar': 'Lázaro',
    'Martah': 'Marta',
    'Miriam': 'María',
    'Filipos': 'Felipe',
    'Andreas': 'Andrés',
    'Shimón': 'Simón',
    'Kefa': 'Pedro',
    'Tomáh': 'Tomás',
    'Zekariáhu': 'Zacarías',
    'Adam': 'Hombre, ser humano',
    'Adamáh': 'Tierra, suelo',
    'Néfesh': 'Alma, persona, garganta',
    'Neshamáh': 'Aliento de vida',
    'jai': 'Vida',
    'najash': 'Serpiente',
    'Ishmael': 'El escucha',
    'Itzjak': 'Reirá',
    'Ribkah': 'Unida',
    'Esav': 'Peludo',
    'Iosef': 'Él añadirá',
    'Káin': 'Adquirido',
    'Hével': 'Vapor',
    'Nóaj': 'El que porta descanso',
    'Shem': 'Nombre',
    'Jam': 'Caliente',
    'Iáfet': 'Ampliar',
    'Kenáan': 'Canaán',
    'Beersheva': 'Pozo del juramento',
    'Shabat': 'Descanso, sábado',
    'Torah': 'Instrucción, ley',
    'Mishkán': 'Tabernáculo',
    'leviím': 'Levitas',
    'Mishpat': 'Juicio, proceso legal',
    'Tzedakáh': 'Justicia',
    'Jésed': 'Bondad, misericordia',
    'ketuvim': 'Escrituras',
    'kedoshim': 'Santos, apartados'
}


def get_book_info(book_key: str) -> Dict[str, Any]:
    """Get book information by key."""
    if book_key not in BOOKS_INFO:
        raise ValueError(f"Unknown book: {book_key}")
    return BOOKS_INFO[book_key]


def get_available_books() -> list:
    """Get list of available book keys."""
    return list(BOOKS_INFO.keys())

